reporting_jurisdiction = [
    'AL',
    'AK',
    'AS',
    'AZ',
    'AK',
    'CA',
    'CI',
    'CO',
    'MP',
    'CT',
    'DE',
    'DC',
    'FM',
    'FL',
    'GA',
    'GU',
    'HI',
    'HO',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LC',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NZ',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'PH',
    'PR',
    'MH',
    'PW',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'VI',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY',
]

sample_location = ['wwtp', 'upstream']

institution_type = [
    'not institution specific',
    'correctional',
    'long term care - nursing home',
    'long term care - assisted living',
    'other long term care',
    'short stay acute care hospital',
    'long term acute care hospital',
    'child day care',
    'k12',
    'higher ed dorm',
    'higher ed other',
    'social services shelter',
    'other residential building',
    'ship',
    'airplane',
]

wwtp_jurisdictions = [
    'AL',
    'AK',
    'AS',
    'AZ',
    'AK',
    'CA',
    'CO',
    'MP',
    'CT',
    'DE',
    'DC',
    'FM',
    'FL',
    'GA',
    'GU',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'PR',
    'MH',
    'PW',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'VI',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY',
]

yes_no_empty = [
    'yes',
    'no',
    None
]

sample_type = [
    '24-hr flow-weighted composite',
    '12-hr flow-weighted composite',
    '8-hr flow-weighted composite',
    '6-hr flow-weighted composite',
    '3-hr flow-weighted composite',
    '24-hr time-weighted composite',
    '12-hr time-weighted composite',
    '8-hr time-weighted composite',
    '6-hr time-weighted composite',
    '3-hr time-weighted composite',
    '24-hr manual composite',
    '12-hr manual composite',
    '8-hr manual composite',
    '6-hr manual composite',
    '3-hr manual composite',
    'grab',
]

sample_matrix = [
    'raw wastewater',
    'post grit removal',
    'primary sludge',
    'primary effluent ',
    'secondary sludge',
    'secondary effluent',
    'septage',
    'holding tank'
]

solids_separation = [
    'filtration',
    'centriguation',
    'none',
    None
]

concentration_method = [
    'membrane filtration with addition of mgcl2',
    'membrane filtration with sample acidification',
    'membrane filtration with acidification and mgcl2',
    'membrane filtration with no amendment',
    'peg precipitation',
    'ultracentrifugation',
    'skimmed milk flocculation',
    'beef extract flocculation',
    'promega wastewater large volume tna capture kit',
    'centricon ultrafiltration',
    'amicon ultrafiltration',
    'hollow fiber dead end ultrafiltration',
    'none'
]

extraction_method = [
    'qiagen allprep powerviral dna/rna kit',
    'qiagen allprep powerfecal dna/rna kit',
    'qiange allprep dna/rna kit',
    'qiagen rneasy powermicrobiome kit',
    'qiagen powerwater kit',
    'qiagen rneasy kit',
    'promega ht tna kit',
    'promega automated tna kit',
    'promega manual tna kit',
    'promega wastewater large volume tna capture kit',
    'nuclisens automated magnetic bead extraction kit',
    'nuclisens manual magnetic bead extraction kit',
    'phenol chloroform'
]
